name: Electron

on:
  push:
    branches:
    - release/production

jobs:
  build_on_mac:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Add OSX certificate
      env:
        CERTIFICATE_OSX_P12: ${{ secrets.CERTIFICATE_OSX_P12 }}
        CERTIFICATE_OSX_PASSWORD: ${{ secrets.CERTIFICATE_OSX_PASSWORD }}
      run: |
        chmod +x build/add-osx-cert.sh
        ./build/add-osx-cert.sh
    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      run: |
        yarn
        electron-forge publish --platform darwin
      env:
        CI: true