name: Electron
on:
  push:
    branches:
      - production

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: electron
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: build
      run: |
        yarn
        electron-forge publish
      env:
        CI: true