name: Build macOS

on:
  push:
    branches:
    - release/production

jobs:
  build:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Add OSX certificate
      env:
        CERTIFICATE_OSX_P12: ${{ secrets.CERTIFICATE_OSX_P12 }}
        CERTIFICATE_OSX_PASSWORD: ${{ secrets.CERTIFICATE_OSX_PASSWORD }}
      run: |
        chmod +x build/mac/cert.sh
        ./build/mac/cert.sh
    - name: install dependencies
      run: yarn
    - name: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      run: npx electron-forge publish --platform=darwin